import {useEffect,useState} from 'react';
export function Notice({children,tone=''}){return <div className={'notice '+tone}>{children}</div>;}
export function NumberControl({label,value,min=0,max=100,step=1,unit='',onChange,onReset}){
 const [draft,setDraft]=useState(String(value)),[error,setError]=useState('');
 useEffect(()=>{setDraft(String(value));setError('');},[value]);
 function apply(){const n=Number(draft);if(!draft.trim()||!Number.isFinite(n)||n<min||n>max){setError(`Enter ${min}-${max} ${unit}`);return;}if(n!==value)onChange(n);setError('');}
 return <div className="number-control"><label>{label}<span>{unit}</span></label><div className="number-row"><button aria-label={`Decrease ${label}`} disabled={value<=min} onClick={()=>onChange(Math.max(min,value-step))}>-</button><input aria-label={`${label} slider`} type="range" min={min} max={max} step={step} value={Number(draft)||value} onChange={e=>setDraft(e.target.value)} onPointerUp={e=>onChange(Number(e.currentTarget.value))} onKeyUp={e=>onChange(Number(e.currentTarget.value))}/><input aria-label={label} className="exact" inputMode="decimal" value={draft} onChange={e=>setDraft(e.target.value)} onPointerUp={e=>{const el=e.currentTarget;if(el.selectionStart===el.selectionEnd)el.setSelectionRange(el.value.length,el.value.length);}} onBlur={apply} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();e.currentTarget.blur();}if(e.key==='Escape'){setDraft(String(value));setError('');}}}/><button aria-label={`Increase ${label}`} disabled={value>=max} onClick={()=>onChange(Math.min(max,value+step))}>+</button></div>{onReset?<button className="text-button" onClick={onReset}>Reset to inherited value</button>:null}{error?<small className="error">{error}</small>:null}<small>{min}-{max} {unit} / step {step}</small></div>;
}
export function TextField({label,value,onChange,multiline=false,disabled=false}){const [draft,setDraft]=useState(value??'');useEffect(()=>setDraft(value??''),[value]);const props={value:draft,disabled,onChange:e=>setDraft(e.target.value),onBlur:()=>draft!==value&&onChange(draft),'aria-label':label};return <label className="field">{label}{multiline?<textarea rows={4} {...props}/>:<input {...props}/>}</label>;}
export function JsonEditor({value,onApply,validate=()=>[]}){const [text,setText]=useState(JSON.stringify(value,null,2)),[error,setError]=useState('');useEffect(()=>{setText(JSON.stringify(value,null,2));setError('');},[value]);return <div className="source-editor"><div className="source-actions"><span>Last valid document remains active.</span><button className="primary" onClick={()=>{try{const p=JSON.parse(text),e=validate(p);if(e.length)throw new Error(e.join('; '));onApply(p);setError('');}catch(e){setError(e.message);}}}>Apply valid draft</button></div><textarea aria-label="JSON source" spellCheck={false} value={text} onChange={e=>setText(e.target.value)}/>{error?<Notice tone="error">{error}</Notice>:null}</div>;}
export function DataTable({headers,children}){return <div className="table-scroll"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>;}
export function rulesText(card){return (card.textTemplate||'No rules text supplied.').replace(/\{([\w.]+)\}/g,(all,key)=>{const [op,index]=key.split('.');const matches=card.effects.filter(e=>e.op===op||e.status===op||op==='hits'&&e.hits!==undefined);const e=matches[(Number(index)||1)-1],v=op==='hits'?e?.hits:e?.amount??e?.stacks;return typeof v==='number'?v:all;});}
export function Card({card,style={}}){return <article className="card-face" style={{fontSize:style.fontSize||17}}><h2>{card.name}</h2><span className="card-kind">{card.class||'Colorless'} / {card.type}</span>{style.art?<img className="card-art" src={style.art} alt={`${card.name} artwork override`} style={{objectFit:style.fit||'cover'}}/>:null}<p>{rulesText(card).replace(/\. /g,'.\n')}</p><div className="card-costs">Action {card.cost??0}{card.staminaCost?` / Stamina ${card.staminaCost}`:''}{card.manaCost?` / Mana ${card.manaCost}`:''}</div><code>{card.id}</code></article>;}
export function download(name,value,mime='application/json'){const blob=new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type:mime});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function loadImage(file){return new Promise((resolve,reject)=>{if(!['image/png','image/webp'].includes(file.type))return reject(new Error('Use PNG or WebP'));if(file.size>2_000_000)return reject(new Error('Image must be below 2 MB'));const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error('Image read failed'));r.readAsDataURL(file);});}
export function PoseImage({src,alt,...props}){const [missing,setMissing]=useState(false);useEffect(()=>setMissing(false),[src]);return missing?<Notice tone="warning">Missing pose asset: {alt}. Replace or repair the reference.</Notice>:<img src={src} alt={alt} onError={()=>setMissing(true)} {...props}/>;}
