import cards from './cards.json';
import deckRules from './deck-rules.json';
import nodesText from './sources/nodes.csv?raw';
import taggingText from './sources/tagging.csv?raw';
import prologue from './sources/prologue.json';
import ui from './sources/w4a-combat.json';
import nodeEffects from './sources/nodeEffects.json';
import poseConfig from './pose-config.json';
import poseAssets from './pose-assets.json';
import {parseCSV,clone,SCHEMA} from './core.mjs';
export const baselineNodes=parseCSV(nodesText);
export const assignments=parseCSV(taggingText);
export const effects=nodeEffects;
export const source={repo:'cehinds/AshenSpire',branch:'dev',commit:'38166cb12a2d8901fce7727aca37cd8d2e7e4b2d'};
export const rules=deckRules.defaults;
export const baseline={schema:SCHEMA,name:'AshenSpire',source,cards:clone(cards),nodes:baselineNodes,styles:{},deck:cards.slice(0,10).map(c=>c.id),owned:Object.fromEntries(cards.map(c=>[c.id,2])),scenes:clone(prologue),scenePlacement:{},lab:{base:40,role:2,selected:true,policy:'overflow',width:1440,height:900,cardScale:100},ui:clone(ui),pose:{...clone(poseConfig.components.starter),id:'local.rogue-attack',name:'Rogue attack / contact study',actor:'rogue',poses:Array.from({length:7},(_,i)=>`ATK-${String(i+1).padStart(2,'0')}`),clips:[],bindings:[{...clone(poseConfig.components.starter.bindings[0]),id:'binding.ambush',name:'Ambush',objectId:'ambush',all:[]}],dependencies:[],assets:clone(poseAssets)},scenario:{name:'Ambush opening',ruleset:'foundations',seed:'ashenspire-fixed-1',cardId:'ambush',prepared:false,playerHp:40,enemyHp:30},erdNative:null};
