import {useEffect,useRef,useState} from 'react';
import {baseline,baselineNodes,assignments,effects,rules,source} from './data.js';
import {clone,reparent,inspectERD,suppliedRows,mapTagRows,toCSV,deckIssues,sizing,undo,redo} from './core.mjs';
import {Notice,NumberControl,TextField,JsonEditor,DataTable,Card,rulesText,download,loadImage,PoseImage} from './Controls.jsx';
import {RepositoryWorkspace} from './RepositoryWorkspace.jsx';
import {GameSettings} from './GameSettings.jsx';
import {CardCreation,WireframeCreation} from './AuthoringCreate.jsx';
import {publicUrl} from './paths.js';
import {sample,validate as validatePose,resolveBindings,CUES} from './native/model/presentationSequence.js';
const row=(cells,key)=><tr key={key}>{cells.map((v,i)=><td key={i}>{v}</td>)}</tr>;
export function Views({ctx}){const components={cards:Cards,decks:Decks,tags:Tags,scenes:Scenes,battlefield:Battlefield,ui:UI,poses:Poses,combat:Combat,project:Project};const Component=components[ctx.ws];return <Component ctx={ctx}/>;}
function Cards({ctx:c}){return <><CardCreation ctx={c}/><CardDocument key={c.card.id} ctx={c}/></>;}
function CardDocument({ctx:c}){const [upgrade,setUpgrade]=useState(false),[proposal,setProposal]=useState('');const {p,card,mode,update,query,choose,tell,setDialog}=c;const patch=(k,v)=>update(n=>n.cards=n.cards.map(q=>q.id===card.id?{...q,[k]:v}:q));
 if(mode==='JSON')return <JsonEditor key={card.id} value={card} validate={q=>q.id!==card.id?['Card ID must remain unchanged']:!q.name||!Array.isArray(q.effects)?['Card requires name and effects']:[]} onApply={q=>update(n=>n.cards=n.cards.map(a=>a.id===card.id?q:a))}/>;
 if(mode==='Prompt')return <div className="padded"><h2>Review a proposal</h2><p>Paste proposed card JSON. This bench never calls an assistant or executes code.</p><textarea className="proposal-input" aria-label="Proposed card JSON" value={proposal} onChange={e=>setProposal(e.target.value)} placeholder='{"id":"ambush","name":"Ambush",...}'/><button className="primary" onClick={()=>{try{const q=JSON.parse(proposal);if(q.id!==card.id||!q.name||!Array.isArray(q.effects))throw new Error('Proposal needs this ID, a name and an effects array');setDialog({kind:'proposal',value:q});}catch(e){tell(e.message);}}}>Review proposed changes</button></div>;
 if(mode==='Table')return <DataTable headers={['Card','ID','Type','Action','Inspect']}>{p.cards.filter(q=>(q.id+' '+q.name).toLowerCase().includes(query.toLowerCase())).map(q=><tr className={q.id===card.id?'active':''} key={q.id}><td>{q.name}</td><td><code>{q.id}</code></td><td>{q.type}</td><td>{q.cost??0}</td><td><button onClick={()=>choose(q.id)}>Inspect</button></td></tr>)}</DataTable>;
 if(mode==='Form')return <div className="padded form-grid"><TextField label="Card name" value={card.name} onChange={v=>patch('name',v)}/><TextField label="Rules template" value={card.textTemplate} onChange={v=>patch('textTemplate',v)} multiline/><TextField label="Flavor text" value={card.flavor} onChange={v=>patch('flavor',v)} multiline/><NumberControl label="Action cost" value={card.cost??0} min={0} max={20} onChange={v=>patch('cost',v)}/><Notice>Source-backed definitions. No engine result is asserted.</Notice></div>;
 return <div className="card-workspace"><div className="canvas-caption">Card preview / readable authoring surface</div><div className="card-stage"><Card card={upgrade&&card.upgrade?{...card,...card.upgrade}:card} style={p.styles[card.id]}/></div><div className="preview-strip"><button className={!upgrade?'selected':''} onClick={()=>setUpgrade(false)}>Base definition</button><button disabled={!card.upgrade} className={upgrade?'selected':''} onClick={()=>setUpgrade(true)}>Upgraded definition</button><span>Same ID in every mode</span></div></div>;
}
function Decks({ctx:c}){const {p,card,mode,query,update,choose,tell}=c;const initial=useRef(clone(p.deck));const [type,setType]=useState('any');const issues=deckIssues(p.deck,p.owned,rules,p.cards);const cards=p.cards.filter(q=>(q.id+' '+q.name).toLowerCase().includes(query.toLowerCase())&&(type==='any'||q.type===type));const add=id=>{if(p.deck.filter(q=>q===id).length>=(p.owned[id]||0))return tell('No more owned copies in this sandbox');update(n=>n.deck.push(id),'Sandbox copy added');};
 return <div className="padded"><Notice>Sandbox collection: two owned copies per inspected card. Not a live run or equipment inventory.</Notice><label className="field compact">Type<select value={type} onChange={e=>setType(e.target.value)}><option value="any">Any type</option>{[...new Set(p.cards.map(q=>q.type))].map(t=><option key={t}>{t}</option>)}</select></label>{mode==='Validation'?<><h2>Deck validation</h2><p>Inspected defaults: minimum {rules.deckMinSize}; maximum {rules.deckMaxUnlimited?'unlimited':rules.deckMaxSize}; ordered play {rules.playInDeckOrder?'enabled':'disabled'}.</p>{issues.length?issues.map(e=><Notice tone="error" key={e}>{e}</Notice>):<Notice tone="good">Valid against declared sandbox limits.</Notice>}</>:<div className="deck-columns"><section><h3>Collection <span>{cards.length}</span></h3>{cards.map(q=><div className={'deck-row '+(q.id===card.id?'active':'')} key={q.id}><button draggable onDragStart={e=>e.dataTransfer.setData('text/plain',q.id)} className="row-name" onClick={()=>choose(q.id,'decks')}>{q.name}<small>{q.type} / Action {q.cost??0}</small></button><button disabled={p.deck.filter(id=>id===q.id).length>=p.owned[q.id]} onClick={()=>add(q.id)}>Add</button></div>)}</section><section className="deck-target" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain');if(p.cards.some(q=>q.id===id))add(id);}}><h3>Deck <span>{p.deck.length} cards</span></h3>{p.deck.map((id,i)=><div className="deck-row" key={`${id}-${i}`}><button className="row-name" onClick={()=>choose(id,'decks')}>{p.cards.find(q=>q.id===id).name}<small>Copy {p.deck.slice(0,i+1).filter(q=>q===id).length}</small></button><button aria-label={`Remove ${id} copy ${i+1}`} onClick={()=>update(n=>n.deck.splice(i,1),'Sandbox copy removed')}>Remove</button></div>)}</section></div>}<div className="sticky-actions"><button className="primary" disabled={issues.length>0} onClick={()=>{initial.current=clone(p.deck);tell('Sandbox deck confirmed locally');}}>Confirm deck</button><button onClick={()=>update(n=>n.deck=clone(initial.current),'Deck session restored')}>Cancel session changes</button><small>{issues[0]||'Valid sandbox deck'}</small></div></div>;
}
function Tags({ctx:c}){const {p,node,mode,query,choose,update,tell}=c;const [native,setNative]=useState(p.erdNative?.raw||null),[pageIndex,setPageIndex]=useState(0),[entityId,setEntityId]=useState(''),[mapping,setMapping]=useState({id:'id',parent:'parentId',label:'label'}),[overwrite,setOverwrite]=useState(false);const input=useRef();const pages=native?inspectERD(native):[],page=pages[pageIndex],entity=page?.nodes.find(n=>n.id===entityId),rows=page&&entity?suppliedRows(page,entityId):[],mapped=mapTagRows(rows,mapping,p.nodes),filtered=p.nodes.filter(n=>(n.id+' '+n.label).toLowerCase().includes(query.toLowerCase()));
 function load(obj){const pages=inspectERD(obj);setNative(obj);setPageIndex(0);setEntityId(pages[0].nodes.find(n=>n.type==='entity')?.id||'');setOverwrite(false);}
 if(mode==='ERD 0.2.4')return <div className="native-pane"><div className="native-note">Native Workbench 0.2.4 / independent document <a href={publicUrl('native/erd-workbench-0.2.4.html')} target="_blank" rel="noreferrer">Open full window</a></div><iframe title="ERD Workbench 0.2.4" src={publicUrl('native/erd-workbench-0.2.4.html')} sandbox="allow-scripts allow-same-origin allow-downloads allow-modals"/></div>;
 if(mode==='CSV')return <div className="padded"><Notice>Authored rows and original columns. Unknown fields remain intact.</Notice><pre>{toCSV(p.nodes)}</pre></div>;
 if(mode==='Import')return <div className="padded"><h2>Choose, map, complete, review</h2><p>Native v2/v3 projects supported. Only explicitly imported rows become candidates. Schema-only and generated samples supply zero game records.</p><div className="button-row"><button className="primary" onClick={()=>input.current.click()}>Choose native .erd.json</button><button onClick={()=>load({format:'erd-workbench',version:3,appVersion:'0.2.4',pages:[{id:'example',name:'Mapping example',nodes:[{id:'diagram-tag',type:'entity',name:'Tag',fields:[{name:'id'},{name:'parentId'},{name:'label'}]}],edges:[],data:{'diagram-tag':{mode:'imported',rows:[{id:'proposal:workbench-example',parentId:'card',label:'Workbench example'}]}}}]})}>Load mapping example</button></div><input ref={input} hidden type="file" accept=".json" onChange={async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{if(f.size>40_000_000)throw new Error('Native file exceeds 40 MB');load(JSON.parse(await f.text()));tell('Native project loaded for mapping');}catch(e){tell(e.message);}}}/>{native?<><div className="form-grid"><label className="field">Page<select value={pageIndex} onChange={e=>{const i=Number(e.target.value);setPageIndex(i);setEntityId(pages[i].nodes.find(n=>n.type==='entity')?.id||'');}}>{pages.map((q,i)=><option key={q.id||i} value={i}>{q.name}</option>)}</select></label><label className="field">Entity<select value={entityId} onChange={e=>setEntityId(e.target.value)}><option value="">Choose entity</option>{page?.nodes.filter(q=>q.type==='entity').map(q=><option key={q.id} value={q.id}>{q.name}</option>)}</select></label></div><Notice>{rows.length} supplied records / {mapped.changed} existing IDs. Raw native source is retained.</Notice><div className="form-grid">{Object.entries(mapping).map(([k,v])=><label className="field" key={k}>{k} field<select value={v} onChange={e=>setMapping({...mapping,[k]:e.target.value})}><option value="">Choose column</option>{(entity?.fields||[]).map(f=><option key={f.name}>{f.name}</option>)}</select></label>)}</div>{mapped.errors.map(e=><Notice tone="error" key={e}>{e}</Notice>)}<DataTable headers={['ID','Label','Parent','Action']}>{mapped.proposed.map((q,i)=>row([q.id,q.label,q.parentId,p.nodes.some(n=>n.id===q.id)?'Update existing':'Create'],i))}</DataTable>{mapped.changed?<label className="check"><input type="checkbox" checked={overwrite} onChange={e=>setOverwrite(e.target.checked)}/>I reviewed updates to existing IDs</label>:null}<button className="primary" disabled={!rows.length||mapped.errors.length>0||mapped.changed>0&&!overwrite} onClick={()=>update(n=>{const all=new Map(n.nodes.map(q=>[q.id,q]));mapped.proposed.forEach(({_row,...q})=>all.set(q.id,q));n.nodes=[...all.values()];n.erdNative={raw:native,mapping,page:page.id,entity:entityId};},'Mapped tags applied to local draft')}>Apply reviewed tags to draft</button></>:null}</div>;
 if(mode==='Tree'){const map=new Map(p.nodes.map(q=>[q.id,q]));return <div className="padded tag-tree">{filtered.map(q=>{let depth=0,n=q;while(n.parentId&&depth<10){depth++;n=map.get(n.parentId)||{};}return <button key={q.id} className={q.id===node.id?'selected':''} style={{paddingLeft:16+depth*20}} onClick={()=>choose(q.id)}>{q.label}<code>{q.id}</code><small>{q.parentId||'Root'}</small></button>;})}</div>;}
 return <DataTable headers={['ID','Label','Parent','Domain','Inspect']}>{filtered.map(q=><tr className={q.id===node.id?'active':''} key={q.id}><td><code>{q.id}</code></td><td>{q.label}</td><td>{q.parentId||'Root'}</td><td>{q.domain||'Inherited'}</td><td><button onClick={()=>choose(q.id)}>Inspect</button></td></tr>)}</DataTable>;
}
function Scenes({ctx:c}){const {p,scene,mode,update}=c;const [device,setDevice]=useState('Desktop');const patch=(k,v)=>update(n=>n.scenes.components.sequence.scenes.find(q=>q.id===scene.id)[k]=v);
 if(mode==='JSON')return <JsonEditor value={p.scenes} validate={q=>!Array.isArray(q?.components?.sequence?.scenes)?['Native scene sequence required']:q.components.sequence.scenes.some(s=>!s.id||!s.name)?['Scene IDs and names required']:[]} onApply={q=>update(n=>n.scenes=q)}/>;
 if(mode==='Words & sound')return <div className="padded form-grid"><TextField label="Scene name" value={scene.name} onChange={v=>patch('name',v)}/><TextField label="Speaker" value={scene.speaker} onChange={v=>patch('speaker',v)}/><TextField label="Scene words" value={scene.text} onChange={v=>patch('text',v)} multiline/><TextField label="Music" value={scene.music} onChange={v=>patch('music',v)}/><TextField label="Stinger" value={scene.stinger} onChange={v=>patch('stinger',v)}/><Notice>Native scene fields retained. Full prologue renderer and host are disconnected.</Notice></div>;
 return <div className="padded"><div className="button-row"><label>Target <Device value={device} change={setDevice}/></label><span className="pill">Composition preview</span></div><div className={'scene-canvas '+device.toLowerCase()}><img className="scene-background" src={publicUrl('assets/scene-'+(scene.id==='warmth'?0:scene.id==='year'?2:1)+'.webp')} alt="Source opening art sample"/>{scene.character?<img className="traveller" src={publicUrl('assets/rogue-ATK-01.webp')} alt="Rogue composition study" style={{left:(p.scenePlacement[scene.id]?.x??50)+'%',bottom:(p.scenePlacement[scene.id]?.y??12)+'%'}}/>:null}<div className="dialogue"><span>{scene.speaker}</span><p>{scene.text}</p></div></div><Notice>Source-art composition study. Backgrounds other than Warmth/The Burning use an explicit Night sample. Exact camera/reveal and host acknowledgement are not connected.</Notice></div>;
}
function Battlefield({ctx:c}){const {p,mode,update}=c;const [device,setDevice]=useState('Desktop');const dim=sizing(p.lab.base,p.lab.role,p.lab.selected,p.lab.policy);
 if(mode==='JSON')return <JsonEditor value={p.lab} validate={q=>!Number.isFinite(q.base)||q.base<30||q.base>80||![1,2].includes(q.role)||!['overflow','cap'].includes(q.policy)?['Invalid sizing proposal']:[]} onApply={q=>update(n=>n.lab=q)}/>;
 return <div className="padded"><div className="button-row"><label>Target <Device value={device} change={setDevice}/></label><span className="pill">Proposal only</span></div>{mode==='Compare'?<div className="compare-grid">{['Desktop','Tablet','Phone'].map(d=><div key={d}><h3>{d}</h3><div className={'lab-mini '+d.toLowerCase()}><span>Battlefield</span><div className="mini-hand">Card region</div></div></div>)}</div>:<div className={'lab-canvas '+device.toLowerCase()}><div className="battlefield-zone"><span>Battlefield / stage boundary</span>{mode==='Sizing diagnostics'?<img className="sizing-sprite" src={publicUrl('assets/rogue-ATK-01.webp')} alt="Source sprite sizing diagnostic" style={{height:dim.displayed+'%'}}/>:null}</div><div className="hand-zone">{p.cards.slice(0,5).map(q=><div style={{fontSize:p.lab.cardScale*.11}} key={q.id}>{q.name}</div>)}</div></div>}<Notice tone={dim.overflow?'warning':''}>{p.lab.base}% x {p.lab.role} x {p.lab.selected?1.5:1} = {dim.authored}% stage height. {p.lab.policy==='cap'?`Explicitly capped to ${dim.displayed}%.`:'Overflow stays visible; no hidden clamp.'}</Notice></div>;
}
function uiProblems(q){if(!q||typeof q!=='object'||!q.sizing?.bands)return ['Native sizing.bands required'];const values=Object.values(q.sizing.bands);return values.some(v=>!Number.isFinite(v)||v<0)||Math.abs(values.reduce((a,b)=>a+b,0)-100)>.0001?['Nonnegative band values must sum to 100']:[];}
function ConfigPreview({ui,device}){return <div className={'config-preview '+device.toLowerCase()}>{Object.entries(ui.sizing.bands).map(([name,size])=><div key={name} style={{height:size+'%'}}><span>{name}</span><strong>{size}%</strong></div>)}</div>;}
function UI({ctx:c}){return <><WireframeCreation ctx={c}/><UILayout ctx={c}/></>;}
function UILayout({ctx:c}){const {p,mode,update}=c;if(mode==='JSON')return <JsonEditor value={p.ui} validate={uiProblems} onApply={q=>update(n=>n.ui=q)}/>;return <div className="padded">{mode==='Compare'?<><div className="compare-grid">{['Desktop','Tablet','Phone'].map(d=><div key={d}><h3>{d}</h3><ConfigPreview ui={p.ui} device={d}/></div>)}</div><Notice>Geometry preview. Runtime layout modes, clamps and saved-build renderer require the UI Studio host.</Notice></>:<><h2>Combat layout bands</h2><p>Changing a band transfers slack to the scene band. Native fields and variables remain intact.</p><ConfigPreview ui={p.ui} device="Desktop"/><div className="form-grid">{Object.entries(p.ui.sizing.bands).filter(([k])=>k!=='scene').map(([k,v])=><NumberControl key={k} label={k+' band'} value={v} min={0} max={v+p.ui.sizing.bands.scene} unit="%" onChange={next=>update(n=>{n.ui.sizing.bands.scene-=next-v;n.ui.sizing.bands[k]=next;})}/>)}</div><Notice>Sum {Object.values(p.ui.sizing.bands).reduce((a,b)=>a+b,0)}%. Structural checks only; full config compiler not connected.</Notice></>}</div>;}
function Poses({ctx:c}){const {p,mode,card,update,poseSelected,setPoseSelected,clipId,setClipId}=c;const [time,setTime]=useState(0),[playing,setPlaying]=useState(false),[loop,setLoop]=useState(true),[speed,setSpeed]=useState(1);const sampled=sample(p.pose,Math.min(time,p.pose.duration));const patch=fn=>update(n=>{fn(n.pose);const e=validatePose(n.pose);if(e.length)throw new Error(e[0]);},'Native presentation draft updated');
 useEffect(()=>{if(!playing)return;let request,last=performance.now();const tick=now=>{const dt=(now-last)*speed;last=now;setTime(t=>{const next=t+dt;if(next>p.pose.duration){if(loop)return next%p.pose.duration;setPlaying(false);return p.pose.duration;}return next;});request=requestAnimationFrame(tick);};request=requestAnimationFrame(tick);return()=>cancelAnimationFrame(request);},[playing,p.pose.duration,loop,speed]);
 if(mode==='JSON')return <JsonEditor value={p.pose} validate={validatePose} onApply={q=>update(n=>n.pose=q)}/>;
 if(mode==='Bindings'){const b=p.pose.bindings[0];return <div className="padded"><h2>Binding resolution</h2>{b?<><TextField label="Binding object ID" value={b.objectId} onChange={v=>patch(q=>q.bindings[0].objectId=v)}/><TextField label="Event" value={b.event} onChange={v=>patch(q=>q.bindings[0].event=v)}/><TextField label="Required tags, comma separated" value={b.all.join(', ')} onChange={v=>patch(q=>q.bindings[0].all=v.split(',').map(s=>s.trim()).filter(Boolean))}/></>:<Notice>No binding supplied in this project.</Notice>}<pre>{JSON.stringify(resolveBindings(p.pose,{provider:'ashenspire',kind:'card',objectId:card.id,event:'actionResolved',tags:[],energySpent:card.cost||0,staminaSpent:card.staminaCost||0,manaSpent:card.manaCost||0}),null,2)}</pre></div>;}
 return <div className="pose-workspace"><div className="pose-stage"><span className="canvas-caption">Native sampler / {sampled.pose}</span><PoseImage key={sampled.pose} src={p.pose.assets['pose:'+sampled.pose]||publicUrl(`assets/rogue-${sampled.pose}.webp`)} alt={`Rogue ${sampled.pose}`}/><span className="anchor-label">Uniform pose sampling / native attachment anchors retained</span></div><div className="timeline"><div className="button-row"><button className="primary" onClick={()=>setPlaying(!playing)}>{playing?'Pause':'Play'}</button><button onClick={()=>{setPlaying(false);setTime(0);}}>Restart</button><label>Speed <select value={speed} onChange={e=>setSpeed(Number(e.target.value))}>{[.5,1,2].map(s=><option key={s} value={s}>{s}x</option>)}</select></label><label className="check"><input type="checkbox" checked={loop} onChange={e=>setLoop(e.target.checked)}/>Loop</label><span>{Math.round(time)} / {p.pose.duration} ms</span></div><input type="range" aria-label="Pose timeline" min={0} max={p.pose.duration} value={Math.min(time,p.pose.duration)} onChange={e=>{setPlaying(false);setTime(Number(e.target.value));}}/><div className="pose-strip">{p.pose.poses.map((pose,i)=><button key={i} className={i===sampled.poseIndex?'selected':''} onClick={()=>{setPoseSelected(i);setTime(i*p.pose.duration/p.pose.poses.length);}}><PoseImage src={p.pose.assets['pose:'+pose]||publicUrl(`assets/rogue-${pose}.webp`)} alt={pose}/><span>{pose}</span></button>)}</div>{p.pose.clips.map(clip=><button className={'clip-track '+(clip.id===clipId?'selected':'')} key={clip.id} onClick={()=>setClipId(clip.id)}>{clip.effect} / {clip.cue} + {clip.offset} ms / {clip.duration} ms</button>)}</div></div>;
}
function Combat({ctx:c}){const {p,mode,update}=c;const patch=(k,v)=>update(n=>n.scenario[k]=v);if(mode==='JSON')return <JsonEditor value={p.scenario} validate={q=>!q.name||!['legacy','foundations'].includes(q.ruleset)||!p.cards.some(a=>a.id===q.cardId)?['Valid name, ruleset and card required']:[]} onApply={q=>update(n=>n.scenario=q)}/>;return <div className="padded"><Notice tone="warning"><strong>Engine not connected.</strong> No mock results or receipts. Edit and export an unapplied scenario.</Notice><h2>{p.scenario.name}</h2><div className="form-grid"><TextField label="Scenario name" value={p.scenario.name} onChange={v=>patch('name',v)}/><TextField label="Fixed seed" value={p.scenario.seed} onChange={v=>patch('seed',v)}/><label className="field">Ruleset<select value={p.scenario.ruleset} onChange={e=>patch('ruleset',e.target.value)}><option value="legacy">Legacy</option><option value="foundations">Foundations</option></select></label><label className="field">Card<select value={p.scenario.cardId} onChange={e=>patch('cardId',e.target.value)}>{p.cards.map(q=><option key={q.id} value={q.id}>{q.name}</option>)}</select></label><NumberControl label="Player HP" value={p.scenario.playerHp} min={1} max={999} onChange={v=>patch('playerHp',v)}/><NumberControl label="Enemy HP" value={p.scenario.enemyHp} min={1} max={999} onChange={v=>patch('enemyHp',v)}/></div><label className="check"><input type="checkbox" checked={p.scenario.prepared} onChange={e=>patch('prepared',e.target.checked)}/>Player starts Prepared</label><button disabled title="Real engine handshake required">Run real engine</button><h3>Connection contract</h3><p>Snapshot + content digest / ruleset / seed / scenario revision / applied acknowledgement / receipts.</p></div>;}
function Project({ctx:c}){const {p,h,mode,setH,changedCards,changedNodes,setDialog}=c;
 if(mode==='Game settings')return <GameSettings ctx={c}/>;
 if(['Repositories','Files','Builds'].includes(mode))return <RepositoryWorkspace mode={mode} ctx={c}/>;
 if(mode==='History')return <div className="padded"><h2>Local document history</h2><p>{h.past.length} undo steps / {h.future.length} redo steps. Source files untouched.</p><div className="button-row"><button disabled={!h.past.length} onClick={()=>setH(undo)}>Undo</button><button disabled={!h.future.length} onClick={()=>setH(redo)}>Redo</button><button onClick={()=>setDialog('reset')}>Review reset to source</button></div><Notice>Browser recovery is not a checkout backup. Export a portable workbench checkpoint.</Notice></div>;
 if(mode==='Assets')return <div className="padded"><h2>Source asset library</h2><div className="asset-grid">{Array.from({length:7},(_,i)=><figure key={i}><img src={publicUrl(`assets/rogue-ATK-${String(i+1).padStart(2,'0')}.webp`)} alt={`Rogue source attack pose ${i+1}`}/><figcaption>ATK-{String(i+1).padStart(2,'0')}</figcaption></figure>)}</div><p>art/dagger-outfits-2026-09-19/frames/rogue-duelist. Opening background samples: assets-mobile/prologue.</p></div>;
 if(mode==='Sources')return <div className="padded"><h2>Original inspected files</h2><div className="source-links">{['rogue.mjs','deckRules.mjs','nodes.csv','tagging.csv','familyNodes.csv','nodeVariables.csv','nodeRelations.csv','nodeEffects.json','prologue.json','w4a-combat.json'].map(f=><a key={f} href={publicUrl('source/'+f)} target="_blank" rel="noreferrer">{f}<span>Read original snapshot</span></a>)}</div><Notice>Original inspected snapshot. Open a local Git repository through Project tools; Files and Builds use its isolated checkout.</Notice></div>;
 return <div className="padded"><h2>AshenSpire project</h2><p className="lede">A shared authoring workbench with native tools and honest previews.</p><div className="metric-grid"><div><strong>{p.cards.length}</strong><span>Rogue definitions</span></div><div><strong>{p.nodes.length}</strong><span>Authored tag nodes</span></div><div><strong>0.2.4</strong><span>Native ERD Workbench</span></div></div><p><a href={publicUrl('responsive-preview.html')} target="_blank" rel="noreferrer">Open responsive editor preview</a></p><h3>Change review</h3><DataTable headers={['Owner','Local change']}>{[['Card definitions',changedCards+' changed'],['Tag vocabulary',changedNodes+' changed or added'],['Presentation sidecars',Object.keys(p.styles).length+' styles'],['Deck sandbox',p.deck.length+' cards'],['Generated game files','Untouched']].map(([k,v])=>row([k,v],k))}</DataTable><div className="button-row"><button className="primary" onClick={()=>download('AshenedSpire-editor.json',p)}>Export whole project</button><button onClick={()=>setDialog('review')}>Import / review project</button><button onClick={()=>setDialog('health')}>Preview health</button></div><Notice>Source commit {source.commit}. Authoring snapshot stays separate from repository checkouts. Use local repositories, native document saves, settings promotion, Files and Builds for source work. Cards, battlefield and effect adapters remain separate.</Notice></div>;
}
function Device({value,change}){return <select value={value} onChange={e=>change(e.target.value)}>{['Desktop','Tablet','Phone'].map(d=><option key={d}>{d}</option>)}</select>;}

export function Inspector({ctx:c}){const {p,ws,card,node,scene,update,tell,switchWs,setMode,poseSelected,clipId,setClipId}=c;const image=useRef(),poseImage=useRef();const patchCard=(k,v)=>update(n=>n.cards=n.cards.map(q=>q.id===card.id?{...q,[k]:v}:q));const patchStyle=(k,v)=>update(n=>n.styles[card.id]={...n.styles[card.id],[k]:v});const patchPose=fn=>update(n=>{fn(n.pose);const e=validatePose(n.pose);if(e.length)throw new Error(e[0]);});const clip=p.pose.clips.find(q=>q.id===clipId);
 if(ws==='cards'||ws==='decks')return <><h2>{card.name}</h2><code>{card.id}</code><p>{rulesText(card)}</p><small>src/content/cards/rogue.js</small>{ws==='decks'?<><button className="primary" disabled={p.deck.filter(id=>id===card.id).length>=p.owned[card.id]} onClick={()=>update(n=>n.deck.push(card.id),'Sandbox copy added')}>Add selected copy</button><p>{p.deck.filter(id=>id===card.id).length} in deck / {p.owned[card.id]} sandbox owned</p></>:<><NumberControl label="Rules font size" value={p.styles[card.id]?.fontSize??17} min={12} max={24} unit="px" onChange={v=>patchStyle('fontSize',v)} onReset={()=>update(n=>{if(n.styles[card.id])delete n.styles[card.id].fontSize;})}/><TextField label="Card name" value={card.name} onChange={v=>patchCard('name',v)}/><button onClick={()=>image.current.click()}>Import card artwork</button><input ref={image} hidden type="file" accept="image/png,image/webp" onChange={async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{patchStyle('art',await loadImage(f));}catch(e){tell(e.message);}}}/>{p.styles[card.id]?.art?<><label className="field">Art fit<select value={p.styles[card.id]?.fit||'cover'} onChange={e=>patchStyle('fit',e.target.value)}><option>cover</option><option>contain</option></select></label><button onClick={()=>update(n=>delete n.styles[card.id].art)}>Remove artwork override</button></>:null}<p>Presentation overrides are sidecars; export whole project to retain them.</p></>}<button onClick={()=>{switchWs('poses');if(p.pose.bindings[0])patchPose(q=>q.bindings[0].objectId=card.id);}}>Open animation binding</button><button onClick={()=>switchWs('tags')}>Inspect tags</button></>;
 if(ws==='tags'){const usage=assignments.filter(q=>q.tagId===node.id);return <><h2>{node.label}</h2><code>{node.id}</code><TextField label="Tag label" value={node.label} onChange={v=>update(n=>n.nodes=n.nodes.map(q=>q.id===node.id?{...q,label:v}:q))}/><label className="field">Parent<select value={node.parentId} onChange={e=>update(n=>n.nodes=reparent(n.nodes,node.id,e.target.value))}><option value="">Root</option>{p.nodes.filter(q=>q.id!==node.id).map(q=><option value={q.id} key={q.id}>{q.label} ({q.id})</option>)}</select></label><h3>Usage</h3><p>{usage.length} direct assignments in source snapshot</p>{usage.slice(0,5).map((q,i)=><small key={i}>{q.family} / {q.scope||'global'} / {q.objectId}</small>)}<h3>Mechanic definition</h3><pre>{effects[node.id]?JSON.stringify(effects[node.id],null,2):'No explicit mechanic entry. A label alone grants no effect.'}</pre><small>parentId is ancestry; dotted IDs are opaque.</small></>;}
 if(ws==='scenes'){const patch=(k,v)=>update(n=>n.scenes.components.sequence.scenes.find(q=>q.id===scene.id)[k]=v);return <><h2>{scene.name}</h2><code>{scene.id}</code><NumberControl label="Scene duration" value={scene.seconds||5} min={.1} max={60} step={.1} unit="sec" onChange={v=>patch('seconds',v)}/><label className="check"><input type="checkbox" checked={scene.enabled!==false} onChange={e=>patch('enabled',e.target.checked)}/>Enabled</label><label className="check"><input type="checkbox" checked={!!scene.waitForInput} onChange={e=>patch('waitForInput',e.target.checked)}/>Wait for input</label><TextField label="Speaker" value={scene.speaker} onChange={v=>patch('speaker',v)}/><TextField label="Scene words" value={scene.text} onChange={v=>patch('text',v)} multiline/><h3>Placement proposal</h3>{['x','y'].map(k=><NumberControl key={k} label={'Traveller '+k} value={p.scenePlacement[scene.id]?.[k]??(k==='x'?50:12)} min={0} max={100} unit="%" onChange={v=>update(n=>n.scenePlacement[scene.id]={...n.scenePlacement[scene.id],[k]:v})}/>)}<small>Placement is a sidecar; native renderer adapter required.</small></>;}
 if(ws==='battlefield'){const dim=sizing(p.lab.base,p.lab.role,p.lab.selected,p.lab.policy);return <><h2>Stage sizing</h2><NumberControl label="Sprite base height" value={p.lab.base} min={30} max={80} unit="%" onChange={v=>update(n=>n.lab.base=v)} onReset={()=>update(n=>n.lab.base=40)}/><label className="field">Role multiplier<select value={p.lab.role} onChange={e=>update(n=>n.lab.role=Number(e.target.value))}><option value={1}>Normal / 1x</option><option value={2}>Boss / 2x</option></select></label><label className="check"><input type="checkbox" checked={p.lab.selected} onChange={e=>update(n=>n.lab.selected=e.target.checked)}/>Selected / 1.5x</label><label className="field">Fit policy<select value={p.lab.policy} onChange={e=>update(n=>n.lab.policy=e.target.value)}><option value="overflow">Show authored overflow</option><option value="cap">Explicit cap to stage</option></select></label><NumberControl label="Card preview scale" value={p.lab.cardScale} min={50} max={150} unit="%" onChange={v=>update(n=>n.lab.cardScale=v)}/><Notice>{dim.authored}% authored / {dim.displayed}% displayed</Notice><small>Stage height units. Formation fitting, alpha/body/shadow bounds need renderer integration.</small></>;}
 if(ws==='ui')return <><h2>Combat config</h2><code>ui/scenes/w4a-combat.json</code><h3>Authored sections</h3>{Object.keys(p.ui).map(k=><p key={k}>{k}</p>)}<Notice>Variables/fractions retained in JSON. Compare is geometry, not the saved-build renderer.</Notice><button onClick={()=>setMode('JSON')}>Edit native JSON</button></>;
 if(ws==='poses')return <><h2>{clip?'Effect clip':'Pose sequence'}</h2><NumberControl label="Sequence duration" value={p.pose.duration} min={100} max={30000} step={100} unit="ms" onChange={v=>patchPose(q=>q.duration=v)}/><button onClick={()=>poseImage.current.click()}>Replace selected pose PNG/WebP</button><input ref={poseImage} hidden type="file" accept="image/png,image/webp" onChange={async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{const art=await loadImage(f);patchPose(q=>q.assets['pose:'+q.poses[poseSelected]]=art);}catch(e){tell(e.message);}}}/><button onClick={()=>{const id='clip.'+(crypto.randomUUID?.()||crypto.getRandomValues(new Uint32Array(2)).join('-'));patchPose(q=>q.clips.push({id,effect:'shieldBash',cue:'contact',offset:0,duration:430,anchor:'torso',x:0,y:0,size:180,rotation:0,opacity:1,layer:'front',travel:false,muted:false}));setClipId(id);}}>Add effect clip</button>{clip?<><TextField label="Effect ID" value={clip.effect} onChange={v=>patchPose(q=>q.clips.find(a=>a.id===clipId).effect=v)}/><label className="field">Cue<select value={clip.cue} onChange={e=>patchPose(q=>q.clips.find(a=>a.id===clipId).cue=e.target.value)}>{Object.keys(CUES).map(q=><option key={q}>{q}</option>)}</select></label><NumberControl label="Effect duration" value={clip.duration} min={60} max={30000} step={10} unit="ms" onChange={v=>patchPose(q=>q.clips.find(a=>a.id===clipId).duration=v)}/><NumberControl label="Effect offset" value={clip.offset} min={-30000} max={30000} step={10} unit="ms" onChange={v=>patchPose(q=>q.clips.find(a=>a.id===clipId).offset=v)}/><button onClick={()=>{patchPose(q=>q.clips=q.clips.filter(a=>a.id!==clipId));setClipId('');}}>Remove clip</button><small>Native reference/timing. Effect artwork catalog not bundled; stage previews poses only.</small></>:null}<p>{validatePose(p.pose).length?validatePose(p.pose).join('; '):'Native model validates this presentation project.'}</p><small>Presentation only / engine override disconnected</small></>;
 if(ws==='combat')return <><h2>Runner identity</h2><Notice tone="warning">Not connected</Notice><h3>Required</h3><p>Engine snapshot<br/>Content digest<br/>Ruleset<br/>Fixed seed<br/>Scenario revision<br/>Applied acknowledgement</p><p>Workshop source access needed before execution integration.</p></>;
 if(ws==='project'&&['Repositories','Files','Builds'].includes(c.mode))return <><h2>Repository workflow</h2><p>Open a local Git repository, manage branches, inspect files, save reviewed source edits, then build or test declared scripts.</p><button onClick={()=>setMode('Repositories')}>Repositories</button><button onClick={()=>setMode('Files')}>Files</button><button onClick={()=>setMode('Builds')}>Builds</button><h3>Document ownership</h3><p>Repository saves change isolated local checkouts. Draft undo applies only to authoring documents.</p><small>Local checkout tools never push or sign in to a remote service. Native document saves and settings promotion require explicit review.</small></>;
 return <><h2>Project identity</h2><p>{source.repo}</p><code>dev @ 38166cb</code><h3>Local changes</h3><p>{c.changedCards} cards<br/>{c.changedNodes} nodes<br/>{c.h.past.length} undo steps</p><button onClick={()=>download('AshenedSpire-editor.json',p)}>Export whole project</button><button onClick={()=>c.setDialog('review')}>Import / review</button><small>Browser recovery and exported authoring files. Repository workspace has separate explicit save controls.</small></>;
}
